export const GET_ALL_DESTINATIONS_FILTER_REQUEST = 'GET_ALL_DESTINATIONS_FILTER_REQUEST'
export const GET_ALL_DESTINATIONS_FILTER_SUCCESS = 'GET_ALL_DESTINATIONS_FILTER_SUCCESS'
export const GET_ALL_DESTINATIONS_FILTER_FAILURE = 'GET_ALL_DESTINATIONS_FILTER_FAILURE'

export const POST_DESTINATIONS_REQUEST = 'POST_DESTINATIONS_REQUEST'
export const POST_DESTINATIONS_SUCCESS = 'POST_DESTINATIONS_SUCCESS'
export const POST_DESTINATIONS_FAILURE = 'POST_DESTINATIONS_FAILURE'

export const GET_ALL_DESTINATIONS_REQUEST = 'GET_ALL_DESTINATIONS_REQUEST'
export const GET_ALL_DESTINATIONS_SUCCESS = 'GET_ALL_DESTINATIONS_SUCCESS'
export const GET_ALL_DESTINATIONS_FAILURE = 'GET_ALL_DESTINATIONS_FAILURE'

export const DELETE_BY_ID_DESTINATIONS_REQUEST = 'DELETE_BY_ID_DESTINATIONS_REQUEST'
export const DELETE_BY_ID_DESTINATIONS_SUCCESS = 'DELETE_BY_ID_DESTINATIONS_SUCCESS'
export const DELETE_BY_ID_DESTINATIONS_FAILURE = 'DELETE_BY_ID_DESTINATIONS_FAILURE'