export const GET_ALL_DESTINATIONS_REQUEST = 'GET_ALL_DESTINATIONS_REQUEST'
export const GET_ALL_DESTINATIONS_SUCCESS = 'GET_ALL_DESTINATIONS_SUCCESS'
export const GET_ALL_DESTINATIONS_FAILURE = 'GET_ALL_DESTINATIONS_FAILURE'