export const PUT_RADIUS_REQUEST = 'PUT_RADIUS_REQUEST'
export const PUT_RADIUS_SUCCESS = 'PUT_RADIUS_SUCCESS'
export const PUT_RADIUS_FAILURE = 'PUT_RADIUS_FAILURE'

export const GET_RADIUS_REQUEST = 'GET_RADIUS_REQUEST'
export const GET_RADIUS_SUCCESS = 'GET_RADIUS_SUCCESS'
export const GET_RADIUS_FAILURE = 'GET_RADIUS_FAILURE'