export const GET_ALL_USER_FILTER_REQUEST = 'GET_ALL_USER_FILTER_REQUEST'
export const GET_ALL_USER_FILTER_SUCCESS = 'GET_ALL_USER_FILTER_SUCCESS'
export const GET_ALL_USER_FILTER_FAILURE = 'GET_ALL_USER_FILTER_FAILURE'

export const GET_ALL_USER_REQUEST = 'GET_ALL_USER_REQUEST'
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS'
export const GET_ALL_USER_FAILURE = 'GET_ALL_USER_FAILURE'

export const PUT_BY_USERNAME_MAKE_ADMIN_REQUEST = 'PUT_BY_USERNAME_MAKE_ADMIN_REQUEST'
export const PUT_BY_USERNAME_MAKE_ADMIN_SUCCESS = 'PUT_BY_USERNAME_MAKE_ADMIN_SUCCESS'
export const PUT_BY_USERNAME_MAKE_ADMIN_FAILURE = 'PUT_BY_USERNAME_MAKE_ADMIN_FAILURE'

export const PUT_BY_USERNAME_MAKE_STAFF_REQUEST = 'PUT_BY_USERNAME_MAKE_STAFF_REQUEST'
export const PUT_BY_USERNAME_MAKE_STAFF_SUCCESS = 'PUT_BY_USERNAME_MAKE_STAFF_SUCCESS'
export const PUT_BY_USERNAME_MAKE_STAFF_FAILURE = 'PUT_BY_USERNAME_MAKE_STAFF_FAILURE'

export const PUT_BY_USERNAME_MAKE_COURIER_REQUEST = 'PUT_BY_USERNAME_MAKE_COURIER_REQUEST'
export const PUT_BY_USERNAME_MAKE_COURIER_SUCCESS = 'PUT_BY_USERNAME_MAKE_COURIER_SUCCESS'
export const PUT_BY_USERNAME_MAKE_COURIER_FAILURE = 'PUT_BY_USERNAME_MAKE_COURIER_FAILURE'

export const PUT_BY_USERNAME_MAKE_DISABLED_REQUEST = 'PUT_BY_USERNAME_MAKE_DISABLED_REQUEST'
export const PUT_BY_USERNAME_MAKE_DISABLED_SUCCESS = 'PUT_BY_USERNAME_MAKE_DISABLED_SUCCESS'
export const PUT_BY_USERNAME_MAKE_DISABLED_FAILURE = 'PUT_BY_USERNAME_MAKE_DISABLED_FAILURE'