export const GET_ALL_USER_FILTER_REQUEST = 'GET_ALL_USER_FILTER_REQUEST'
export const GET_ALL_USER_FILTER_SUCCESS = 'GET_ALL_USER_FILTER_SUCCESS'
export const GET_ALL_USER_FILTER_FAILURE = 'GET_ALL_USER_FILTER_FAILURE'