export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE'

export const PUT_PROFILE_REQUEST = 'PUT_PROFILE_REQUEST'
export const PUT_PROFILE_SUCCESS = 'PUT_PROFILE_SUCCESS'
export const PUT_PROFILE_FAILURE = 'PUT_PROFILE_FAILURE'