export const GET_CHARTS_USER_REQUEST = 'GET_CHARTS_USER_REQUEST'
export const GET_CHARTS_USER_SUCCESS = 'GET_CHARTS_USER_SUCCESS'
export const GET_CHARTS_USER_FAILURE = 'GET_CHARTS_USER_FAILURE'

export const GET_CHARTS_TASK_REQUEST = 'GET_CHARTS_TASK_REQUEST'
export const GET_CHARTS_TASK_SUCCESS = 'GET_CHARTS_TASK_SUCCESS'
export const GET_CHARTS_TASK_FAILURE = 'GET_CHARTS_TASK_FAILURE'