export const POST_TASK_REQUEST = 'POST_TASK_REQUEST'
export const POST_TASK_SUCCESS = 'POST_TASK_SUCCESS'
export const POST_TASK_FAILURE = 'POST_TASK_FAILURE'

export const GET_ALL_TASK_REQUEST = 'GET_ALL_TASK_REQUEST'
export const GET_ALL_TASK_SUCCESS = 'GET_ALL_TASK_SUCCESS'
export const GET_ALL_TASK_FAILURE = 'GET_ALL_TASK_FAILURE'

export const DELETE_BY_ID_TASK_REQUEST = 'DELETE_BY_ID_TASK_REQUEST'
export const DELETE_BY_ID_TASK_SUCCESS = 'DELETE_BY_ID_TASK_SUCCESS'
export const DELETE_BY_ID_TASK_FAILURE = 'DELETE_BY_ID_TASK_FAILURE'

export const GET_ALL_TASK_FINISHED_REQUEST = 'GET_ALL_TASK_FINISHED_REQUEST'
export const GET_ALL_TASK_FINISHED_SUCCESS = 'GET_ALL_TASK_FINISHED_SUCCESS'
export const GET_ALL_TASK_FINISHED_FAILURE = 'GET_ALL_TASK_FINISHED_FAILURE'

export const GET_ALL_TASK_UNFINISHED_REQUEST = 'GET_ALL_TASK_UNFINISHED_REQUEST'
export const GET_ALL_TASK_UNFINISHED_SUCCESS = 'GET_ALL_TASK_UNFINISHED_SUCCESS'
export const GET_ALL_TASK_UNFINISHED_FAILURE = 'GET_ALL_TASK_UNFINISHED_FAILURE'