export const POST_TASK_REQUEST = 'POST_TASK_REQUEST'
export const POST_TASK_SUCCESS = 'POST_TASK_SUCCESS'
export const POST_TASK_FAILURE = 'POST_TASK_FAILURE'

export const GET_ALL_TASK_REQUEST = 'GET_ALL_TASK_REQUEST'
export const GET_ALL_TASK_SUCCESS = 'GET_ALL_TASK_SUCCESS'
export const GET_ALL_TASK_FAILURE = 'GET_ALL_TASK_FAILURE'